### ISSUE TITLE
Negative values in output predicted matrix

### ISSUE THREAD

**Issue by ytrink** [amitfrish/scBio#15]
Hi,
I am trying to do an absolute deconvolution, using bulk kidney expression and single cell reference data.
In the predicted matrix I am getting negative values which I don't fully understand, since I'm not doing a relative comparison.
I ran the example flu data and saw that also there absolute predictions yield negative values. 
I saw someone else had a similar problem but I didn't fully understand your answer. 
Am I running it wrong or do I not understand the output?
Thanks very much

**Comment by amitfrish** [comment]
Hey,
Sorry for the delay in my answer.
Obtaining negative values using CPM is not an indication for a problem in the usage. 
CPM is different compared to other deconvolution algorithms. While these algorithms intend to predict cell type fractions, CPM is not focused at all in this, In order to obtain cell type fractions, you can use CPM with the  quantifyTypes = T and typeTransformation = T parameters. However, to fully benefit from CPM, you should focus on cell states and not cell types. Basically, CPM provides scores (positive and negative) that correspond to the level of the cell states. Higher scores correlates with higher quantities while lower scores (including negatives) correlates with lower quantities. Since CPM is based on the prediction of hundreds and sometimes thousands of small predictors, it was shown to be highly robust and the negative values do have meanings. We don't provide cell states fractions as the fractions of so many cell states can be misleading. However, you can calculate this by reducing all values in the lowest value and divide by the sum of the new values.  
Anyway, CPM's predicted scores are highly comparable between samples.

I hope it makes sense now,
Amit

**Comment by ytrink** [comment]
Great, thanks so much for the explanation!
