### ISSUE TITLE
question about CPM cell state space

### ISSUE THREAD

**Issue by caiquanyou** [amitfrish/scBio#16]
Hello，I have read your paper about CPM，and I'm wondering the meaning of cell state space？why we need to take it as input while other deconvolution method don't？
best regards
CQY

**Comment by amitfrish** [comment]
Hey CQY,
Sorry for the delayed answer.
CPM is a little bit different than other deconvolution algorithms. It is not focused on calculating the cell type composition, but the cell state composition within each cell type. Therefor, CPM needs to understand the cell space of each cell type and it calculates distances and neighborhoods based on it.

I hope this makes more sense,
Tell me if you need anything else,
Amit

**Comment by caiquanyou** [comment]
I&nbsp; don't really understand what is the input if I want to estimate the cell type proportions and the GEP, I can not get the tutorial&nbsp;
best
cqy



---Original---

**Comment by amitfrish** [comment]
The input is the same as for the case of cell state proportions. The only difference is that for cell type proportions it is advised to create the cell space based on all cell type together and not choosing genes that create specific trajectories (such as activation or development) with these cell type. The idea is that cell type proportions are basically the average of all cell state proportions within each cell type. You want the density of the cell states within each cell type to be close to uniform in order to get appropriate cell type quantities...

I hope this makes more sense.

**Comment by caiquanyou** [comment]
and now get this error:
> x_cpm_prop<-CPM(SCData = true_counts,SCLabels = scdata$distinctive_clusters,BulkData = x,cellSpace = cell_space,quantifyTypes = T)
[1] "Model size was switched to: 6"
[1] "Selecting cells for each iteration"
Error in min(currXY) : invalid 'type' (list) of argument

**Comment by amitfrish** [comment]
Make sure you use the right classes for the inputs. Can you please attach the classes and the dim of each input parameter?
