### ISSUE TITLE
"length of 'dimnames' [2] not equal to array extent"

### ISSUE THREAD

**Issue by aabordba** [amitfrish/scBio#4]
[1] "Selecting cells for each iteration"
[1] "Number of iteration: 978"
[1] "Running CPM, this may take a few minutes"
|=================================================================================================| 100%
Error in { : 
  task 10 failed - "length of 'dimnames' [2] not equal to array extent"

Set up my variables (scData, scLabels, bulkData, and scCellSpace) in csv files and loaded using read.table, then converting to matrices and vectors as required. Note: scCellSpace is 2d. Unclear why I'm getting this error. I checked lengths and dimensions of the matrices and the rownames/colnames and they seem to match properly. I checked the dimnames of my variables and compared to the example data and do not see an issue. Tested both in 1 core or multi-cores.

I also tried the example data and that worked fine.

**Comment by amitfrish** [comment]
Can you print the dims of all your inputs and the number of cells you have from each cell type (use table on the labels for that). In addition, tell me if you change any of the parameters of CPM (neighborhoodSize, modelSize, minSelection).
This might help me to understand what is the problem.

Amit

**Comment by amitfrish** [comment]
I just tried something and got the same problem as you. It seems that the neighborhoodSize you selected is higher than the number of cells you got in at least one of your cell types. The default value for this parameter is 10 so make sure you have more than 10 cells in each cell type of alternatively lower this value. Generally, we don't suggest to use cell types with small amount of cells since the cell space for these cell types is less informative and the results are not as robust as for the other cell types. However, it is possible by tuning the parameters. Tell me if this solved your problem.

Amit

**Comment by aabordba** [comment]
Hi Amit,

Yes, this seems to be the problem. I had one cell type that was only 7 cells. It's not a particularly important cell type in my analysis, so do you recommend to just throw it out or reduce the neighborhood size to 7?

Best
Aarash

**Comment by amitfrish** [comment]
In general, the cell space of cell types with a small number of cells won't be informative. I wouldn't suggest lowering the neighborhood size for this cell type. You should just exclude it from the analysis to get accurate results for the rest of the cell types.
