### ISSUE TITLE
cellspace selection and output interpretation

### ISSUE THREAD

**Issue by gdagstn** [amitfrish/scBio#8]
Hi,

I have two questions related to cell type abundance prediction and cell population map interpretation. I am mostly interested in deconvoluting cell types in bulk data, rather than cell states. To do that I ran CPM in "absolute mode", using normalized counts from my scRNA  and normalized median counts from the data (GTEx). 

1) if as a cell-state space I use a UMAP dimensionality reduction, which separates pretty well the cell types in the scRNA data, does this meet the assumptions used by scBio? I am asking because, quoting from your documentation: 

> In order to get a proper cell-type predictions, it is crutial to set the cell space to be as homogeneous as possible. One option is to create the cell space based on genes which have the lowest variance across the cells (but small amount of zeros).

Whereas, if I'm not wrong, UMAP is normally done on the first N series of loadings of a PCA on normalized scRNA counts. PCA itself uses the most variable genes to identify PCs explaining most of the variance in the dataset. As a result, UMAP separates cell types pretty well (in that the 2D projection has a decent overlap with the result of clustering) and is not "as homogenous as possible", rather the opposite. Am I interpreting this right?

2) I'm not exactly sure as to how to interpret the output, i.e.  the "predicted cell abundance matrix" since I also have negative values. Is there something wrong in the input possibly? They are in both cases normalized counts, so all positive doubles.

Thanks in advance for your time.

**Comment by amitfrish** [comment]
Hey,
You asked two very good questions. Here are my answers:
1. It is perfectly fine to use UMAP or any other dim reduction algorithm. We always suggest on using PCA since CPM is calculating euclidean distances based on the cell space but UMAP works pretty good as well. About the homogeneous issue, to efficiently calculate cell-type prediction, CPM requires that each cell type will be homogeneous. Of course that between cell types there is a lot of variation but this is taken cared by the labels you give as input. On the other hand, variation within cell types is the focus of CPM so it will look for it even in cell type prediction. High variation within the space of each cell type might reduce the accuracy of the method.
I know this sounds strange for single cell people but in order to use CPM properly (only in the case of cell type prediction), you should create a different cell space for each cell type and than just combine them (rbind of matrices) into one cell space. There will be overlap between the cell spaces of different cell types but you don't need to care about this since CPM looks on each cell space separetely, based on the labels. In that case, it is better to not use the most variable genes in order to keep the homogeneity within each cell type.
2. If you choose to do cell type prediction, just add "quantifyTypes = T, typeTransformation = T" to the run and you'll get the absolute fractions for each cell type in the "cellTypePredictions" output. If you run a relative analysis, choose "typeTransformation = F" and you'll get negative scores again. These score represents the difference compared to a control group in a relative analysis and are monotonic to the fractions in the absolute analysis (however in that case just use the transformation).

I hope that all of this make sense to you.
Tell me if you need anything else,
Amit
