### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Szhang19** [amitfrish/scBio#9]
Hi,

Do you have any solution about the following error? Thanks.
task 11 failed - "object of type 'S4' is not subsettable"
Calls: CPM -> CPMMain -> %dopar2% -> <Anonymous>
Execution halted

Shaojun

**Comment by amitfrish** [comment]
It's hard for me to understand what is the problem just based on that.
It is probably due to wrong inputs for the CPM function.
Did you try running CPM using the example data? Make sure your input data objects are similar in their structures and classes to the example data objects.
If this doesn't work, please add here the classes and dimensions of your data objects as well as the syntax you used for running CPM.

Amit

**Comment by Szhang19** [comment]
Thanks, Amit.
I changed the classes from matrix to data.frame. It worked. 👍 

Shaojun
